"""
Parallel Code Generators
Generates UI, Backend, Database, and Deployment code in parallel tracks
"""

import asyncio
import json
import os
from typing import Optional
from dataclasses import dataclass
import aiohttp


@dataclass
class GeneratorConfig:
    """Configuration for code generators"""
    v0_api_key: str = ""
    fireworks_api_key: str = ""


class ParallelCodeGenerators:
    """
    Generates complete full-stack code in 4 parallel tracks:
    - Track A: UI Components (shadcn/ui + Tailwind)
    - Track B: Backend (tRPC + API routes)
    - Track C: Database (Prisma schema)
    - Track D: Deployment (Vercel config)
    """

    def __init__(self, config: Optional[GeneratorConfig] = None):
        self.config = config or GeneratorConfig(
            v0_api_key=os.getenv("V0_API_KEY", ""),
            fireworks_api_key=os.getenv("FIREWORKS_API_KEY", "")
        )

    async def generate_all(
        self,
        spec: str,
        blueprint: dict,
        project_id: str
    ) -> dict[str, str]:
        """
        Execute all 4 generator tracks in parallel.
        Returns dictionary of file_path -> file_content
        """
        # Run all generators in parallel
        results = await asyncio.gather(
            self._generate_ui_components(spec, blueprint, project_id),
            self._generate_backend_code(spec, blueprint, project_id),
            self._generate_database_schema(spec, blueprint, project_id),
            self._generate_deployment_config(spec, blueprint, project_id),
            self._generate_app_layout(spec, blueprint, project_id),
            self._generate_lib_files(spec, blueprint, project_id),
            return_exceptions=True
        )

        # Merge all generated files
        all_files = {}
        for result in results:
            if isinstance(result, dict):
                all_files.update(result)
            elif isinstance(result, Exception):
                print(f"Generator error: {result}")

        return all_files

    async def _generate_ui_components(
        self,
        spec: str,
        blueprint: dict,
        project_id: str
    ) -> dict[str, str]:
        """Track A: Generate UI components using shadcn/ui patterns"""
        files = {}

        ui_components = blueprint.get("ui_components", [])

        for component in ui_components:
            component_name = component.get("name", "Component")
            component_type = component.get("type", "component")
            shadcn_base = component.get("shadcn_base", "Card")
            props = component.get("props", [])
            description = component.get("description", "")

            # Generate component code
            code = self._generate_component_code(
                component_name, component_type, shadcn_base, props, description
            )

            # Determine file path
            if component_type == "page":
                files[f"app/{component_name.lower()}/page.tsx"] = code
            else:
                files[f"components/{component_name}.tsx"] = code

        return files

    def _generate_component_code(
        self,
        name: str,
        component_type: str,
        shadcn_base: str,
        props: list,
        description: str
    ) -> str:
        """Generate React component code"""

        # Build props interface
        props_interface = self._build_props_interface(name, props)

        # Import statements based on shadcn base
        imports = self._get_shadcn_imports(shadcn_base)

        # Component body based on type
        component_body = self._get_component_body(name, component_type, shadcn_base, props)

        return f'''/**
 * {name} - {description}
 * Auto-generated by Agentic CodeForge
 */

"use client";

import {{ useState, useEffect }} from "react";
{imports}
import {{ cn }} from "@/lib/utils";

{props_interface}

export function {name}({{ {", ".join(props)} }}: {name}Props) {{
{component_body}
}}

export default {name};
'''

    def _build_props_interface(self, name: str, props: list) -> str:
        """Build TypeScript props interface"""
        prop_types = {
            "posts": "Post[]",
            "post": "Post",
            "user": "User",
            "users": "User[]",
            "items": "Item[]",
            "item": "Item",
            "onLoadMore": "() => void",
            "onSubmit": "(data: any) => void",
            "onSelect": "(value: string) => void",
            "onChange": "(value: any) => void",
            "onLike": "(id: string) => void",
            "onRetweet": "(id: string) => void",
            "onApply": "() => void",
            "onAddToCart": "(id: string) => void",
            "onCheckout": "() => void",
            "onUpload": "(files: File[]) => void",
            "onSearch": "(query: string) => void",
            "onSave": "(data: any) => void",
            "isLiked": "boolean",
            "isFollowing": "boolean",
            "isOwnProfile": "boolean",
            "isWishlisted": "boolean",
            "hasUnviewed": "boolean",
            "autoPlay": "boolean",
            "maxLength": "number",
            "maxFiles": "number",
            "count": "number",
            "columns": "number",
            "cursor": "string",
            "query": "string",
            "placeholder": "string",
            "content": "string",
            "currentPath": "string",
            "userId": "string",
            "postId": "string",
            "jobId": "string",
            "productId": "string",
            "blockId": "string",
            "pageId": "string",
            "currentPageId": "string",
            "imageUrl": "string",
            "videoUrl": "string",
            "mediaUrls": "string[]",
            "products": "Product[]",
            "product": "Product",
            "jobs": "Job[]",
            "job": "Job",
            "comments": "Comment[]",
            "replies": "Reply[]",
            "notifications": "Notification[]",
            "unreadCount": "number",
            "topics": "Topic[]",
            "stories": "Story[]",
            "photos": "Photo[]",
            "filters": "Filter[]",
            "categories": "Category[]",
            "blocks": "Block[]",
            "pages": "Page[]",
            "path": "Breadcrumb[]",
            "collaborators": "Collaborator[]",
            "data": "any[]",
            "events": "Event[]",
            "experience": "Experience",
            "education": "Education",
            "skill": "string",
            "level": "string",
            "status": "string",
            "company": "Company",
            "stats": "ProfileStats",
            "conversations": "Conversation[]",
            "cart": "CartItem[]",
            "order": "Order",
            "review": "Review",
            "amount": "number",
            "onSuccess": "(data: any) => void",
            "price": "number",
            "discount": "number",
            "reel": "Reel",
        }

        lines = [f"interface {name}Props {{"]
        for prop in props:
            prop_type = prop_types.get(prop, "any")
            optional = "?" if prop.startswith("on") or prop in ["cursor", "query", "placeholder"] else ""
            lines.append(f"  {prop}{optional}: {prop_type};")
        lines.append("}")

        return "\n".join(lines)

    def _get_shadcn_imports(self, shadcn_base: str) -> str:
        """Get import statements for shadcn component"""
        imports_map = {
            "Card": 'import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card";',
            "Button": 'import { Button } from "@/components/ui/button";',
            "Input": 'import { Input } from "@/components/ui/input";',
            "Dialog": '''import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";''',
            "Sheet": '''import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";''',
            "ScrollArea": 'import { ScrollArea } from "@/components/ui/scroll-area";',
            "Avatar": 'import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";',
            "Badge": 'import { Badge } from "@/components/ui/badge";',
            "NavigationMenu": '''import { NavigationMenu, NavigationMenuItem, NavigationMenuLink, NavigationMenuList } from "@/components/ui/navigation-menu";''',
            "DropdownMenu": '''import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";''',
            "Form": '''import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";''',
            "Table": '''import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";''',
            "Accordion": '''import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";''',
            "Command": '''import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";''',
            "Popover": '''import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";''',
            "Calendar": 'import { Calendar } from "@/components/ui/calendar";',
            "Breadcrumb": '''import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbSeparator } from "@/components/ui/breadcrumb";''',
        }

        base_import = imports_map.get(shadcn_base, imports_map["Card"])
        return f'''{base_import}
import {{ Button }} from "@/components/ui/button";'''

    def _get_component_body(
        self,
        name: str,
        component_type: str,
        shadcn_base: str,
        props: list
    ) -> str:
        """Generate component body based on type"""

        if component_type == "page":
            return f'''  const [isLoading, setIsLoading] = useState(false);

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">{name}</h1>
      <div className="grid gap-4">
        {{/* Content rendered here */}}
      </div>
    </div>
  );'''

        elif component_type == "layout":
            return f'''  return (
    <nav className="flex items-center justify-between p-4 border-b">
      <div className="flex items-center gap-4">
        {{/* Navigation items */}}
      </div>
    </nav>
  );'''

        elif component_type == "feature":
            if shadcn_base == "Dialog":
                return f'''  const [isOpen, setIsOpen] = useState(false);

  return (
    <Dialog open={{isOpen}} onOpenChange={{setIsOpen}}>
      <DialogTrigger asChild>
        <Button>Open {name}</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>{name}</DialogTitle>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          {{/* Feature content */}}
        </div>
      </DialogContent>
    </Dialog>
  );'''
            elif shadcn_base == "Sheet":
                return f'''  const [isOpen, setIsOpen] = useState(false);

  return (
    <Sheet open={{isOpen}} onOpenChange={{setIsOpen}}>
      <SheetTrigger asChild>
        <Button variant="outline">Open {name}</Button>
      </SheetTrigger>
      <SheetContent>
        <SheetHeader>
          <SheetTitle>{name}</SheetTitle>
        </SheetHeader>
        <div className="grid gap-4 py-4">
          {{/* Sheet content */}}
        </div>
      </SheetContent>
    </Sheet>
  );'''

        # Default component
        return f'''  return (
    <Card className="w-full">
      <CardHeader>
        <h3 className="text-lg font-semibold">{name}</h3>
      </CardHeader>
      <CardContent>
        {{/* Component content */}}
      </CardContent>
      <CardFooter className="flex justify-end gap-2">
        <Button variant="outline">Cancel</Button>
        <Button>Submit</Button>
      </CardFooter>
    </Card>
  );'''

    async def _generate_backend_code(
        self,
        spec: str,
        blueprint: dict,
        project_id: str
    ) -> dict[str, str]:
        """Track B: Generate backend tRPC code"""
        files = {}

        api_endpoints = blueprint.get("api_endpoints", [])

        # Group endpoints by namespace
        namespaces = {}
        for endpoint in api_endpoints:
            name_parts = endpoint.get("name", "unknown.action").split(".")
            namespace = name_parts[0] if len(name_parts) > 1 else "main"
            if namespace not in namespaces:
                namespaces[namespace] = []
            namespaces[namespace].append(endpoint)

        # Generate router for each namespace
        for namespace, endpoints in namespaces.items():
            router_code = self._generate_trpc_router(namespace, endpoints)
            files[f"server/routers/{namespace}.ts"] = router_code

        # Generate main router
        files["server/routers/_app.ts"] = self._generate_main_router(list(namespaces.keys()))

        # Generate tRPC context
        files["server/context.ts"] = self._generate_trpc_context()

        # Generate tRPC server setup
        files["server/trpc.ts"] = self._generate_trpc_setup()

        # Generate API route handler
        files["app/api/trpc/[trpc]/route.ts"] = self._generate_api_route()

        return files

    def _generate_trpc_router(self, namespace: str, endpoints: list) -> str:
        """Generate tRPC router for a namespace"""
        procedures = []

        for endpoint in endpoints:
            name_parts = endpoint.get("name", "").split(".")
            procedure_name = name_parts[1] if len(name_parts) > 1 else name_parts[0]
            method = endpoint.get("method", "query")
            input_schema = endpoint.get("input_schema", "{}")
            description = endpoint.get("description", "")
            auth_required = endpoint.get("auth_required", False)

            procedure = self._generate_procedure(
                procedure_name, method, input_schema, description, auth_required
            )
            procedures.append(procedure)

        return f'''/**
 * {namespace} router
 * Auto-generated by Agentic CodeForge
 */

import {{ z }} from "zod";
import {{ router, publicProcedure, protectedProcedure }} from "../trpc";
import {{ TRPCError }} from "@trpc/server";

export const {namespace}Router = router({{
{chr(10).join(procedures)}
}});
'''

    def _generate_procedure(
        self,
        name: str,
        method: str,
        input_schema: str,
        description: str,
        auth_required: bool
    ) -> str:
        """Generate a single tRPC procedure"""
        procedure_type = "protectedProcedure" if auth_required else "publicProcedure"

        # Parse input schema to Zod
        zod_schema = self._convert_to_zod(input_schema)

        return f'''  // {description}
  {name}: {procedure_type}
    .input({zod_schema})
    .{method}(async ({{ ctx, input }}) => {{
      // TODO: Implement {name}
      return {{ success: true, data: null }};
    }}),
'''

    def _convert_to_zod(self, schema_str: str) -> str:
        """Convert TypeScript-like schema to Zod"""
        if not schema_str or schema_str == "{}":
            return "z.object({})"

        # Basic conversion
        schema_str = schema_str.replace("string", "z.string()")
        schema_str = schema_str.replace("number", "z.number()")
        schema_str = schema_str.replace("boolean", "z.boolean()")
        schema_str = schema_str.replace("?:", ".optional():")

        # Wrap in z.object if needed
        if schema_str.startswith("{"):
            return f"z.object({schema_str})"

        return "z.object({})"

    def _generate_main_router(self, namespaces: list) -> str:
        """Generate main app router"""
        imports = "\n".join([f'import {{ {ns}Router }} from "./{ns}";' for ns in namespaces])
        routers = ",\n  ".join([f"{ns}: {ns}Router" for ns in namespaces])

        return f'''/**
 * Main tRPC App Router
 * Auto-generated by Agentic CodeForge
 */

import {{ router }} from "../trpc";
{imports}

export const appRouter = router({{
  {routers}
}});

export type AppRouter = typeof appRouter;
'''

    def _generate_trpc_context(self) -> str:
        """Generate tRPC context"""
        return '''/**
 * tRPC Context
 * Auto-generated by Agentic CodeForge
 */

import { inferAsyncReturnType } from "@trpc/server";
import { FetchCreateContextFnOptions } from "@trpc/server/adapters/fetch";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

export async function createContext(opts: FetchCreateContextFnOptions) {
  const authHeader = opts.req.headers.get("authorization");

  let user = null;
  if (authHeader) {
    const token = authHeader.replace("Bearer ", "");
    const { data } = await supabase.auth.getUser(token);
    user = data.user;
  }

  return {
    user,
    supabase,
  };
}

export type Context = inferAsyncReturnType<typeof createContext>;
'''

    def _generate_trpc_setup(self) -> str:
        """Generate tRPC setup with procedures"""
        return '''/**
 * tRPC Setup
 * Auto-generated by Agentic CodeForge
 */

import { initTRPC, TRPCError } from "@trpc/server";
import { Context } from "./context";
import superjson from "superjson";

const t = initTRPC.context<Context>().create({
  transformer: superjson,
  errorFormatter({ shape }) {
    return shape;
  },
});

export const router = t.router;
export const publicProcedure = t.procedure;

export const protectedProcedure = t.procedure.use(({ ctx, next }) => {
  if (!ctx.user) {
    throw new TRPCError({
      code: "UNAUTHORIZED",
      message: "You must be logged in to perform this action",
    });
  }
  return next({
    ctx: {
      user: ctx.user,
    },
  });
});
'''

    def _generate_api_route(self) -> str:
        """Generate Next.js API route for tRPC"""
        return '''/**
 * tRPC API Route Handler
 * Auto-generated by Agentic CodeForge
 */

import { fetchRequestHandler } from "@trpc/server/adapters/fetch";
import { appRouter } from "@/server/routers/_app";
import { createContext } from "@/server/context";

const handler = (req: Request) =>
  fetchRequestHandler({
    endpoint: "/api/trpc",
    req,
    router: appRouter,
    createContext,
  });

export { handler as GET, handler as POST };
'''

    async def _generate_database_schema(
        self,
        spec: str,
        blueprint: dict,
        project_id: str
    ) -> dict[str, str]:
        """Track C: Generate Prisma schema"""
        files = {}

        database_tables = blueprint.get("database_tables", [])

        # Generate Prisma schema
        models = []
        for table in database_tables:
            model = self._generate_prisma_model(table)
            models.append(model)

        schema = f'''// Prisma Schema
// Auto-generated by Agentic CodeForge

generator client {{
  provider = "prisma-client-js"
}}

datasource db {{
  provider = "postgresql"
  url      = env("DATABASE_URL")
}}

{chr(10).join(models)}
'''

        files["prisma/schema.prisma"] = schema

        # Generate seed file
        files["prisma/seed.ts"] = self._generate_seed_file(database_tables)

        return files

    def _generate_prisma_model(self, table: dict) -> str:
        """Generate Prisma model from table definition"""
        name = table.get("name", "Model")
        fields = table.get("fields", [])
        relations = table.get("relations", [])

        field_lines = []
        for field in fields:
            field_lines.append(f"  {field}")

        # Add relations
        for relation in relations:
            if relation not in field_lines:
                field_lines.append(f"  {relation}")

        return f'''model {name} {{
{chr(10).join(field_lines)}
}}
'''

    def _generate_seed_file(self, tables: list) -> str:
        """Generate database seed file"""
        return '''/**
 * Database Seed File
 * Auto-generated by Agentic CodeForge
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Add your seed data here

  console.log("[OK] Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
'''

    async def _generate_deployment_config(
        self,
        spec: str,
        blueprint: dict,
        project_id: str
    ) -> dict[str, str]:
        """Track D: Generate deployment configuration"""
        files = {}

        deployment_config = blueprint.get("deployment_config", {})
        env_vars = deployment_config.get("env_vars", [])

        # vercel.json
        files["vercel.json"] = json.dumps({
            "buildCommand": "npm run build",
            "outputDirectory": ".next",
            "framework": "nextjs",
            "regions": ["bom1"],
            "functions": {
                "app/api/**/*.ts": {
                    "maxDuration": 30
                }
            }
        }, indent=2)

        # .env.example
        env_example = "\n".join([f"{var}=your_{var.lower()}_here" for var in env_vars])
        files[".env.example"] = f'''# Environment Variables
# Auto-generated by Agentic CodeForge

{env_example}

# Application
NEXT_PUBLIC_APP_URL=http://localhost:3000
'''

        # package.json
        files["package.json"] = self._generate_package_json(spec, project_id)

        # tsconfig.json
        files["tsconfig.json"] = json.dumps({
            "compilerOptions": {
                "target": "ES2017",
                "lib": ["dom", "dom.iterable", "esnext"],
                "allowJs": True,
                "skipLibCheck": True,
                "strict": True,
                "noEmit": True,
                "esModuleInterop": True,
                "module": "esnext",
                "moduleResolution": "bundler",
                "resolveJsonModule": True,
                "isolatedModules": True,
                "jsx": "preserve",
                "incremental": True,
                "plugins": [{"name": "next"}],
                "paths": {
                    "@/*": ["./*"]
                }
            },
            "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
            "exclude": ["node_modules"]
        }, indent=2)

        # tailwind.config.ts
        files["tailwind.config.ts"] = '''import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
'''

        # next.config.js
        files["next.config.js"] = '''/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ["avatars.githubusercontent.com", "lh3.googleusercontent.com"],
  },
  experimental: {
    serverActions: {
      bodySizeLimit: "2mb",
    },
  },
};

module.exports = nextConfig;
'''

        # GitHub Actions workflow
        files[".github/workflows/deploy.yml"] = '''name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
'''

        return files

    def _generate_package_json(self, spec: str, project_id: str) -> str:
        """Generate package.json"""
        return json.dumps({
            "name": f"codeforge-{project_id}",
            "version": "0.1.0",
            "private": True,
            "scripts": {
                "dev": "next dev",
                "build": "next build",
                "start": "next start",
                "lint": "next lint",
                "test": "vitest",
                "test:e2e": "playwright test",
                "db:push": "prisma db push",
                "db:seed": "tsx prisma/seed.ts",
                "generate": "prisma generate"
            },
            "dependencies": {
                "next": "^15.0.0",
                "react": "^18.3.0",
                "react-dom": "^18.3.0",
                "@trpc/client": "^11.0.0",
                "@trpc/server": "^11.0.0",
                "@trpc/react-query": "^11.0.0",
                "@tanstack/react-query": "^5.0.0",
                "@supabase/supabase-js": "^2.45.0",
                "@prisma/client": "^5.0.0",
                "zod": "^3.23.0",
                "superjson": "^2.2.0",
                "@radix-ui/react-dialog": "^1.1.0",
                "@radix-ui/react-dropdown-menu": "^2.1.0",
                "@radix-ui/react-navigation-menu": "^1.2.0",
                "@radix-ui/react-popover": "^1.1.0",
                "@radix-ui/react-scroll-area": "^1.1.0",
                "@radix-ui/react-slot": "^1.1.0",
                "class-variance-authority": "^0.7.0",
                "clsx": "^2.1.0",
                "tailwind-merge": "^2.3.0",
                "tailwindcss-animate": "^1.0.7",
                "lucide-react": "^0.400.0"
            },
            "devDependencies": {
                "typescript": "^5.4.0",
                "@types/node": "^20.0.0",
                "@types/react": "^18.3.0",
                "@types/react-dom": "^18.3.0",
                "tailwindcss": "^3.4.0",
                "postcss": "^8.4.0",
                "autoprefixer": "^10.4.0",
                "eslint": "^8.57.0",
                "eslint-config-next": "^15.0.0",
                "prisma": "^5.0.0",
                "tsx": "^4.0.0",
                "vitest": "^1.6.0",
                "@playwright/test": "^1.44.0"
            }
        }, indent=2)

    async def _generate_app_layout(
        self,
        spec: str,
        blueprint: dict,
        project_id: str
    ) -> dict[str, str]:
        """Generate app layout and main pages"""
        files = {}

        # Root layout
        files["app/layout.tsx"] = '''/**
 * Root Layout
 * Auto-generated by Agentic CodeForge
 */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CodeForge App",
  description: "Auto-generated by Agentic CodeForge",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
'''

        # Providers wrapper
        files["app/providers.tsx"] = '''"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { httpBatchLink } from "@trpc/client";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import superjson from "superjson";

export function Providers({ children }: { children: React.ReactNode }) {
  const [queryClient] = useState(() => new QueryClient());
  const [trpcClient] = useState(() =>
    trpc.createClient({
      links: [
        httpBatchLink({
          url: "/api/trpc",
          transformer: superjson,
        }),
      ],
    })
  );

  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient}>
        {children}
      </QueryClientProvider>
    </trpc.Provider>
  );
}
'''

        # Main page
        files["app/page.tsx"] = '''/**
 * Home Page
 * Auto-generated by Agentic CodeForge
 */

import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="text-center space-y-8">
        <h1 className="text-6xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
          Welcome to CodeForge
        </h1>
        <p className="text-xl text-muted-foreground max-w-2xl">
          Your AI-generated full-stack application is ready.
          Built with Next.js 15, shadcn/ui, tRPC, and Supabase.
        </p>
        <div className="flex gap-4 justify-center">
          <Button size="lg" asChild>
            <Link href="/dashboard">Get Started</Link>
          </Button>
          <Button size="lg" variant="outline" asChild>
            <Link href="/auth/login">Sign In</Link>
          </Button>
        </div>
      </div>
    </main>
  );
}
'''

        # Global styles
        files["app/globals.css"] = '''@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 221.2 83.2% 53.3%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 221.2 83.2% 53.3%;
    --radius: 0.5rem;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: 217.2 91.2% 59.8%;
    --primary-foreground: 222.2 47.4% 11.2%;
    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;
    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;
    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;
    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 224.3 76.3% 48%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
'''

        return files

    async def _generate_lib_files(
        self,
        spec: str,
        blueprint: dict,
        project_id: str
    ) -> dict[str, str]:
        """Generate lib utilities"""
        files = {}

        # Utils
        files["lib/utils.ts"] = '''import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
'''

        # tRPC client
        files["lib/trpc.ts"] = '''import { createTRPCReact } from "@trpc/react-query";
import type { AppRouter } from "@/server/routers/_app";

export const trpc = createTRPCReact<AppRouter>();
'''

        # Supabase client
        files["lib/supabase.ts"] = '''import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Server-side client
export function createServerClient() {
  return createClient(
    supabaseUrl,
    process.env.SUPABASE_SERVICE_ROLE_KEY || supabaseAnonKey
  );
}
'''

        # Types
        files["lib/types.ts"] = '''/**
 * Shared Types
 * Auto-generated by Agentic CodeForge
 */

export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string;
  createdAt: Date;
}

export interface Post {
  id: string;
  content: string;
  authorId: string;
  author?: User;
  createdAt: Date;
  likesCount: number;
  commentsCount: number;
}

export interface Comment {
  id: string;
  content: string;
  authorId: string;
  author?: User;
  postId: string;
  createdAt: Date;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  discountPrice?: number;
  images: string[];
  categoryId: string;
}

export interface Job {
  id: string;
  title: string;
  description: string;
  companyId: string;
  company?: Company;
  location: string;
  type: string;
  salary?: string;
  skills: string[];
  createdAt: Date;
}

export interface Company {
  id: string;
  name: string;
  logo?: string;
  description: string;
  website?: string;
}

export interface Notification {
  id: string;
  type: string;
  message: string;
  read: boolean;
  createdAt: Date;
}

// Generic types
export interface PaginatedResponse<T> {
  items: T[];
  nextCursor?: string;
  hasMore: boolean;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}
'''

        return files


# Standalone test
if __name__ == "__main__":
    async def test_generators():
        generators = ParallelCodeGenerators()
        blueprint = {
            "ui_components": [
                {"name": "PostCard", "type": "component", "shadcn_base": "Card", "props": ["post", "onLike"], "description": "Post card"}
            ],
            "api_endpoints": [
                {"name": "posts.list", "method": "query", "input_schema": "{ cursor?: string }", "description": "List posts", "auth_required": False}
            ],
            "database_tables": [
                {"name": "Post", "fields": ["id String @id", "content String"], "relations": []}
            ],
            "deployment_config": {
                "env_vars": ["DATABASE_URL", "SUPABASE_URL"]
            }
        }
        files = await generators.generate_all("Twitter clone", blueprint, "test123")
        print(f"Generated {len(files)} files")
        for path in files.keys():
            print(f"  - {path}")

    asyncio.run(test_generators())
